<h1>1. Why Loops Are Slow</h1>
In Python, loops are typically slow because:
<ol>
    <li>Python’s interpreter: Every iteration of the loop requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.</li>
    <li>High overhead: Each loop iteration in Python involves additional overhead for function calls, memory access, and index management.</li>
</ol>

In [7]:
import numpy as np
#Example : Looping over arrays in Python
arr=np.array([1,2,3,4,5])
result=[]
for i in arr:
    result.append(i**2);
print(result)
#This works, but it's not efficient. Each loop iteration is slow, especially with large datasets.

[1, 4, 9, 16, 25]


<h1>2. Vectorization: Fixing the Loop Problem</h1>
Vectorization allows you to <strong>perform operations on entire arrays at once, instead of iterating over elements one by one.</strong> This is made possible by NumPy’s optimized C-based backend that executes operations in compiled code, which is much faster than Python loops.

Vectorized operations are also more readable and compact, making your code easier to maintain.

In [8]:
#Example : Vectorized Operation
arr=np.array([1,2,3,4,5])
result=arr**2   #Much faster than looping over array
print(result)

[ 1  4  9 16 25]


<h1>3. Broadcasting: Scaling Arrays Without Extra Memory</h1>
Broadcasting is a powerful feature of NumPy that allows you to <strong>perform operations on arrays of different shapes without creating copies.</strong> It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

In [12]:
#Example : Broadcasting with scalar
arr=np.array([1,2,3,4,5])
result=arr+10  #Here, the scalar 10 is "broadcast" across the entire array, and no extra memory is used.
print(result)

[11 12 13 14 15]


<h1>4. Broadcasting with Arrays of Different Shapes</h1>
Broadcasting becomes more powerful when you apply operations on arrays of <strong>different shapes.</strong> NumPy automatically adjusts the shapes of arrays to make them compatible for element-wise operations, without actually copying the data.

In [14]:
#Example : Broadcasting with Two Arrays
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
result=arr1+arr2   #performs element-wise addition, treating them as if they have the same shape.
print(result)

[ 7  9 11 13 15]


In [16]:
#Example : Broadcasting a 2D Array and a 1D Array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
result=arr1+arr2 # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


<h4>How Broadcasting Works</h4>
<ol>
    <li>Dimensions must be compatible: The size of the trailing dimensions of the arrays must be either the same or one of them must be 1.</li>
    <li>Stretching arrays: If the shapes are compatible, NumPy stretches the smaller array to match the larger one, element-wise, without copying data</li>
</ol>

In [18]:
#Example : Normalizing Data Using Broadcasting
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


<h1>Summary:</h1>
<ul>
    <li>Loops are slow because Python's interpreter adds overhead, making iteration less efficient.</li>
    <li>Vectorization allows you to apply operations to entire arrays at once, greatly improving performance by utilizing NumPy’s optimized C backend.</li>
    <li>Broadcasting enables operations between arrays of different shapes by automatically stretching the smaller array to match the shape of the larger array, without creating additional copies.</li>
    <li>Real-world use: Broadcasting can be used in data science tasks, such as normalizing datasets, without sacrificing memory or performance.</li>
</ul>