<h1>Why NumPy Arrays?</h1><br>
<ul>
    <li>Faster than Python lists (C-optimized)</li>
    <li>Memory-efficient (store data in a contiguous block)</li>
</ul>

<h3>1. Creating NumPy Arrays</h3><br>
 Unlike lists, all elements must have the same data type.

In [2]:
import numpy as np
 
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
 
print(arr1) 
print(arr2)  

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


<h3>2. Checking Array Properties</h3>

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int32


<h3>3. Changing Data Types</h3>

In [4]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int) 

float32
[1 2 3]


<h4>4. Reshaping and Flattening Arrays</h4>

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
