In [58]:
import numpy as np


<h1>Indexing</h1>

In [59]:
arr=np.array([1,2,3])
print(arr[0])
print(arr[-1])

1
3


<h1>Slicing (Extracting part of an array)</h1>

In [60]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
flat=arr.flatten()
print(flat)
print(flat[1:4])   #print from index 1 to 3
print(flat[:3])    #print till index 2
print(flat[::2])    #print every element with step 2

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2 3]
[0 1 2]
[ 0  2  4  6  8 10]


<h2>Slicing returns a view not a copy changes affect original array<h2> 
<h3>This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, changes in the slice affect the original array.</h3>
<h3>This happens for memory efficiency and performance.</h3>

In [61]:
arr=np.array([0,1,2,3,4,5,6])
sliced=arr[0:5]
copy=arr.copy()
print(sliced)
sliced[0]=999
print(sliced)
print(arr)
print(copy)

[0 1 2 3 4]
[999   1   2   3   4]
[999   1   2   3   4   5   6]
[0 1 2 3 4 5 6]


<h2>Fancy indexing and boolean masking</h2>

In [62]:
#Fancy indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
idx=[2,4,5,7]   #Indices to select
print(arr[idx])

#Boolean Masking
arr=np.array([10,20,30,40,50])
mask=arr>20
print(arr[mask])

[3 5 6 8]
[30 40 50]


<h1>Practice</h1>

In [63]:
arr=np.array([[3,5,6],[7,8,4],[3,6,4]])
print(arr.shape)

(3, 3)


In [64]:
arr=np.array([2.4,5.6,3.5,6.4,8.2],dtype='float')
print(arr.dtype)
arr=arr.astype("int64")
print(arr.dtype)

float64
int64


In [65]:
arr=np.array([1,2,3,4,5,6,7])
idx=arr%2==0
print(arr[idx])

[2 4 6]


In [66]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
arr=arr.reshape(3,3)
print(arr.shape)

(9,)
(3, 3)


In [67]:
arr=np.array([344,5565,7,75,7,4,6,45,22,66])
mask=arr>50
print(arr[mask])

[ 344 5565   75   66]
