<h1>Built in Mathematical Functions in NumPy</h1>

<ol>
    <li>np.mean() – Compute the mean (average) of an array.<br>
    np.mean(arr)</li>
    <li>np.std() – Compute the standard deviation of an array.<br>

np.std(arr)</li>

<li>np.var() – Compute the variance of an array.<br>

np.var(arr)</li>

<li>np.min() – Compute the minimum value of an array.<br>

np.min(arr)</li>

<li>np.max() – Compute the maximum value of an array.<br>

np.max(arr)</li>

<li>np.sum() – Compute the sum of all elements in an array.<br>

np.sum(arr)</li>

<li>np.prod() – Compute the product of all elements in an array.<br>

np.prod(arr)</li>

<li>np.median() – Compute the median of an array.<br>

np.median(arr)</li>

<li>np.percentile() – Compute the percentile of an array.<br>

np.percentile(arr, 50)  # For the 50th percentile (median)</li>

<li>np.argmin() – Return the index of the minimum value in an array.<br>

np.argmin(arr)</li>

<li>np.argmax() – Return the index of the maximum value in an array.<br>

np.argmax(arr)</li>

<li>np.corrcoef() – Compute the correlation coefficient matrix of two arrays.<br>

np.corrcoef(arr1, arr2)</li>

<li>np.unique() – Find the unique elements of an array.<br>

np.unique(arr)</li>

<li>np.diff() – Compute the n-th differences of an array.<br>

np.diff(arr)</li>

<li>np.cumsum() – Compute the cumulative sum of an array.<br>

np.cumsum(arr)</li>

<li>np.linspace() – Create an array with evenly spaced numbers over a specified interval.<br>

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10</li>

<li>np.log() – Compute the natural logarithm of an array.<br>

np.log(arr)</li>

<li>np.exp() – Compute the exponential of an array.<br>

np.exp(arr)</li>
</ol>

In [20]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr2=np.array([45,66,34,55,66,55])
arr3=np.array([2,4,56,78,788,99])
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.median(arr))
print(np.percentile(arr, 50))  # For the 50th percentile (median
print(np.argmin(arr)) # index of minimum value
print(np.argmax(arr)) # index of maximum value
print(np.corrcoef(arr2,arr3))  # correlation coefficient of two array
print(np.unique(arr2))
print(np.diff(arr)) # Compute the n-th differences of an array
print(np.cumsum(arr))

3.0
1.4142135623730951
2.0
1
5
15
120
3.0
3.0
0
4
[[1.         0.47918696]
 [0.47918696 1.        ]]
[34 45 55 66]
[1 1 1 1]
[ 1  3  6 10 15]


<h1>These methods are used for performing mathematical and statistical operations with NumPy</h1>