In [1]:
import numpy as np

Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0) <br>
2D array → 2 axes (axis 0 = rows, axis 1 = columns) <br>
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [5]:
arr=np.array([[1,2,3],
     [4,5,6],
     [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Axis 0 (rows) → Operations move down the columns.<br>
Axis 1 (columns) → Operations move across the rows.

In [10]:
print(np.sum(arr,axis=0)) #sum along rows (down each column)
print(np.sum(arr,axis=1)) # sum along column (across each row)

[12 15 18]
[ 6 15 24]


<h1>Indexing in Multidimensional Arrays</h1>

In [13]:
#accessing element
print(arr[1,2])

6


In [17]:
#Extracting parts of an array using slicing
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


<h2>Indexing in 3D Array</h2>

In [24]:
arr3D=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print(arr3D)
print(arr3D.shape)
print(arr3D[0,1,2])  # First sheet, second row, third column
print(arr3D[:,0,:]) #Get the first row from both the sheets

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]


In [26]:
#Selecting data along the axes
first_col=arr[:,0]
print(first_col)  #Get all the rows in first column

[1 4 7]


In [33]:
# Get the first row from each "sheet" in a 3D array
first_row=arr3D[:,0,:]
print(first_row)

[[1 2 3]
 [7 8 9]]


In [35]:
# Replace all elements in column 1 with 0
arr[:,1]=0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


<h1>Summary</h1>
Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)<br>
Indexing works as arr[row, column] for 2D arrays and arr[depth, row, column] for 3D arrays<br>
Slicing allows extracting subarrays<br>
Operations along axes help efficiently manipulate data without loops<br>